"""empty message

Revision ID: 634d3d915de2
Revises: 
Create Date: 2022-02-17 16:53:35.654156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634d3d915de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('contact_number', sa.String(length=10), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('email_address', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration')
    # ### end Alembic commands ###
